### ISSUE TITLE
[BUG]Can't control player

### ISSUE THREAD

**Issue by HuyaSL666** [qbcore-redm-framework/qbr-adminmenu#13]
When an operation is performed on a certain player, the online player who opens the administrator menu again cannot open any player's operation interface
![image](https://github.com/qbcore-redm-framework/qbr-adminmenu/assets/103110822/5094ba80-5f52-4260-82c7-e8001e23682a)

**Comment by DosKit** [comment]
This is Currently Being Worked on as We Speak.

**Comment by DosKit** [comment]
This has been corrected here just waiting on it to be merged. - https://github.com/DosKit/qbr-adminmenu/tree/main

**Comment by HuyaSL666** [comment]
> 这已在这里得到纠正，只是等待合并。- https://github.com/DosKit/qbr-adminmenu/tree/main

Thanks for your contribution
