### ISSUE TITLE
admin menu wont open [BUG]

### ISSUE THREAD

**Issue by stevenm754** [qbcore-redm-framework/qbr-adminmenu#2]
**Describe the bug**
so i have installed the qbr-adminmenu i have set it up on my database with the permissions and also on my server.cfg and it still wont open 
**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qbr-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by GhzGarage** [comment]
The menu opens as it should, please contact in discord for more help
