### ISSUE TITLE
[BUG] Admin Options - Names

### ISSUE THREAD

**Issue by vanadis1** [qbcore-redm-framework/qbr-adminmenu#6]
**Describe the bug**
 When you open the names from the admin options, you cannot close them again.

**To Reproduce**
1. Go to '/admin'
2. Click on 'Admin options and then names active and deactive test'
3. See error

**Expected behavior**

**Additional context**

**Comment by luthanirgi** [comment]
![Screenshot_1944](https://user-images.githubusercontent.com/29462114/176235724-99d51b38-c98a-425d-93e3-8697c129c642.png)

**Comment by IDKFORCE** [comment]
this been fix in lastest!!
